# Generated by Django 3.2.23 on 2023-12-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='additional_link',
            field=models.URLField(blank=True),
        ),
    ]
