# Generated by Django 3.2.23 on 2024-01-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_event_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
