# Generated by Django 3.2.23 on 2024-01-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240115_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_end',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_start',
        ),
    ]
