# Generated by Django 3.2.23 on 2024-01-23 14:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_additional_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='no_alt', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='placeholder', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='blog/'),
        ),
    ]
