# Generated by Django 3.2.23 on 2024-01-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_alt',
            field=models.CharField(max_length=100),
        ),
    ]
