# Generated by Django 3.2.23 on 2024-01-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='event image', max_length=100),
        ),
    ]
